// Re-export useful Prisma-generated types for consumers.
export type {
  Profile,
  Project,
  SocialAccount,
  BrandProfile,
  Objective,
  Competitor,
  SocialPost,
  ContentAsset,
  Report,
  Memory,
  Chat,
  Message,
  ProjectFolder,
  AiJob,
  TokenUsage,
  UserRole,
  OnboardingStep,
  WebsiteSource,
  SocialPlatform,
  SocialSource,
  ObjectiveStatus,
  AssetType,
  ReportType,
  MessageRole,
  AiJobStatus,
  ScheduledPost,
  ScheduledPostStatus,
  ScheduledPostPlatform,
  Recommendation,
  RecommendationStatus,
  RecommendationKind,
  RecommendationImpact,
  ScheduledReport,
  ScheduledReportKind,
  ScheduledReportFrequency,
  Notification,
  AdminAuditLog,
  FeatureFlag,
  CreditAccount,
  CreditTransaction,
  CreditTransactionKind,
  ActionPrice,
  SystemConfig,
} from '@prisma/client';

export { Prisma } from '@prisma/client';
