export const mockData = {
  executive: {
    mrr: { value: "$42,800", delta: "↑ 12% vs mes anterior", isPositive: true, freq: "DIARIO" as const },
    arr: { value: "$513,600", delta: "↑ 12% vs mes anterior", isPositive: true, freq: "DIARIO" as const },
    activeClients: { value: "87", delta: "↑ 3 nuevos", isPositive: true, freq: "DIARIO" as const },
    wauMau: { value: "340 / 890", delta: "↑ 5% ratio", isPositive: true, freq: "EN VIVO" as const },
    churn: { value: "2.3%", delta: "↓ 0.2% vs mes anterior", isPositive: true, freq: "SEMANAL" as const },
    nrr: { value: "108%", delta: "↑ 2% vs mes anterior", isPositive: true, freq: "MENSUAL" as const },
    burnRate: { value: "$18,500/mes", delta: "↓ $500 vs mes anterior", isPositive: true, freq: "SEMANAL" as const },
    runway: { value: "11 meses", delta: "--", isPositive: true, freq: "SEMANAL" as const },
    uptime: { value: "99.97%", delta: "↑ 0.02%", isPositive: true, freq: "EN VIVO" as const },
    pipelineCoverage: { value: "2.4x", delta: "↓ 0.1x", isPositive: false, freq: "SEMANAL" as const },
  },
  product: {
    funnel: [
      { step: "Visitas", value: 1200 },
      { step: "Registros", value: 340 },
      { step: "Onboarding", value: 210 },
      { step: "Aha", value: 148 },
    ],
    activationRate: { value: "43%", delta: "↑ 2%", isPositive: true, freq: "SEMANAL" as const },
    cohortRetention: { value: "71%", delta: "↓ 1%", isPositive: false, freq: "MENSUAL" as const },
    nps: { value: "47", delta: "↑ 3 puntos", isPositive: true, freq: "MENSUAL" as const },
    csat: { value: "4.3/5", delta: "--", isPositive: true, freq: "SEMANAL" as const },
    supportTickets: [
      { id: "T-001", user: "Ana López", category: "Facturación", status: "Abierto", time: "2h" },
      { id: "T-002", user: "Carlos S.", category: "Bug UI", status: "En progreso", time: "5h" },
      { id: "T-003", user: "Empresa X", category: "Duda Onboarding", status: "Cerrado", time: "1d" },
    ],
    topFeatures: [
      { name: "Generador IA", users: 520, percentage: 85 },
      { name: "Dashboard", users: 340, percentage: 55 },
      { name: "Reportes", users: 210, percentage: 34 },
    ]
  },
  commercial: {
    pipeline: [
      { stage: "Lead", count: 120, value: "$60k" },
      { stage: "MQL", count: 68, value: "$45k" },
      { stage: "SQL", count: 31, value: "$28k" },
      { stage: "Propuesta", count: 18, value: "$19k" },
      { stage: "Negociación", count: 9, value: "$12k" },
      { stage: "Ganado", count: 5, value: "$8.5k" },
    ],
    winRate: { value: "28%", delta: "↑ 4%", isPositive: true, freq: "MENSUAL" as const },
    salesCycle: { value: "34 días", delta: "↓ 2 días", isPositive: true, freq: "MENSUAL" as const },
    acv: { value: "$5,800", delta: "↑ $300", isPositive: true, freq: "MENSUAL" as const },
    leadToClient: { value: "4.1%", delta: "↑ 0.5%", isPositive: true, freq: "MENSUAL" as const },
    recentDeals: [
      { company: "TechNova", stage: "Ganado", value: "$12,000", days: 28 },
      { company: "GlobalCorp", stage: "Negociación", value: "$8,500", days: 45 },
      { company: "StartApp", stage: "Propuesta", value: "$4,200", days: 12 },
      { company: "BlueOcean", stage: "SQL", value: "$15,000", days: 5 },
      { company: "GreenLight", stage: "MQL", value: "$3,000", days: 2 },
    ],
    forecast: { current: 38000, target: 50000 },
  },
  marketing: {
    traffic: { value: "8,400", delta: "↑ 15%", isPositive: true, freq: "SEMANAL" as const },
    cvr: { value: "4.0%", delta: "↑ 0.2%", isPositive: true, freq: "SEMANAL" as const },
    mqlSql: { value: "45%", delta: "↓ 2%", isPositive: false, freq: "MENSUAL" as const },
    brandedSearch: { value: "1,200", delta: "↑ 23%", isPositive: true, freq: "MENSUAL" as const },
    sov: { value: "18%", delta: "↑ 1%", isPositive: true, freq: "MENSUAL" as const },
    referralRate: { value: "12%", delta: "--", isPositive: true, freq: "MENSUAL" as const },
    cacChannels: [
      { channel: "Orgánico", cac: "$120" },
      { channel: "Paid", cac: "$850" },
      { channel: "Referidos", cac: "$50" },
      { channel: "Outbound", cac: "$1,200" },
    ],
    communityGrowth: [
      { week: "Sem 1", followers: 4200 },
      { week: "Sem 2", followers: 4350 },
      { week: "Sem 3", followers: 4600 },
      { week: "Sem 4", followers: 5100 },
    ]
  },
  finance: {
    cashBalance: { value: "$203,000", delta: "↑ $15,000", isPositive: true, freq: "DIARIO" as const },
    burnRate: { value: "$18,500", delta: "--", isPositive: true, freq: "MENSUAL" as const },
    runway: { value: "11 meses", delta: "--", isPositive: true, freq: "MENSUAL" as const },
    grossMargin: { value: "72%", delta: "↑ 1%", isPositive: true, freq: "MENSUAL" as const },
    ltv: { value: "$14,200", delta: "↑ $400", isPositive: true, freq: "MENSUAL" as const },
    cac: { value: "$1,850", delta: "↓ $50", isPositive: true, freq: "MENSUAL" as const },
    ltvCac: { value: "7.7x", delta: "↑ 0.2x", isPositive: true, freq: "MENSUAL" as const },
    payback: { value: "8 meses", delta: "--", isPositive: true, freq: "MENSUAL" as const },
    dso: { value: "18 días", delta: "↓ 1 día", isPositive: true, freq: "MENSUAL" as const },
    dpo: { value: "24 días", delta: "--", isPositive: true, freq: "MENSUAL" as const },
    workingCapitalRatio: 1.8,
  }
};
