import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger, } from '@radikal/ui';
/**
 * Small info icon with a tooltip that explains the field was auto-generated
 * from the website analysis. Clicking/editing the parent field remains possible.
 */
export function AutoGeneratedHint({ message = 'Generado automáticamente al analizar tu sitio. Puedes editarlo.', className, }) {
    return (_jsx(TooltipProvider, { delayDuration: 150, children: _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("span", { tabIndex: 0, role: "img", "aria-label": message, className: 'material-symbols-outlined text-[16px] text-slate-400 hover:text-slate-600 cursor-help align-middle ' +
                            (className ?? ''), children: "info" }) }), _jsx(TooltipContent, { className: "max-w-[240px] leading-relaxed", children: message })] }) }));
}
