import {
  Icon,
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@radikal/ui';

interface Props {
  message?: string;
  className?: string;
}

/**
 * Small info icon with a tooltip that explains the field was auto-generated
 * from the website analysis. Clicking/editing the parent field remains possible.
 */
export function AutoGeneratedHint({
  message = 'Generado automáticamente al analizar tu sitio. Puedes editarlo.',
  className,
}: Props) {
  return (
    <TooltipProvider delayDuration={150}>
      <Tooltip>
        <TooltipTrigger asChild>
          <Icon
            name="info"
            tabIndex={0}
            role="img"
            aria-label={message}
            className={
              'text-[16px] text-slate-400 hover:text-slate-600 cursor-help align-middle ' +
              (className ?? '')
            }
          />
        </TooltipTrigger>
        <TooltipContent className="max-w-[240px] leading-relaxed">
          {message}
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}
