import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge, Button, Card } from '@radikal/ui';
import { LogoBlock } from './LogoBlock';
import { AnalyzeBrandButton } from './AnalyzeBrandButton';
export function BrandHero({ projectId, project, companyName, logo, palette, onEdit, }) {
    return (_jsxs(Card, { className: "relative overflow-hidden p-4 sm:p-8 md:p-10 bg-gradient-to-br from-pink-50 via-white to-cyan-50 border-white", children: [_jsx("div", { className: "absolute -top-24 -right-24 w-96 h-96 rounded-full opacity-30 blur-3xl", style: {
                    background: palette[0] && palette[1]
                        ? `radial-gradient(circle, ${palette[0]}, ${palette[1]})`
                        : 'radial-gradient(circle, hsl(var(--color-primary)), hsl(var(--color-secondary)))',
                } }), _jsxs("div", { className: "relative flex flex-col md:flex-row items-center md:items-start gap-4 sm:gap-8", children: [_jsx(LogoBlock, { logo: logo, companyName: companyName, projectId: projectId }), _jsxs("div", { className: "flex-1 min-w-0 text-center md:text-left space-y-3", children: [_jsx("p", { className: "text-[10px] font-black uppercase tracking-[0.3em] text-[hsl(var(--color-primary))]", children: "Identidad de Marca" }), _jsx("h1", { className: "font-display text-2xl sm:text-4xl md:text-5xl font-black leading-tight break-words", children: companyName }), _jsxs("div", { className: "flex flex-wrap items-center gap-3 justify-center md:justify-start", children: [project?.industry && _jsx(Badge, { variant: "primary", children: project.industry }), project?.industry_custom && (_jsx(Badge, { variant: "secondary", children: project.industry_custom })), project?.website_url && (_jsxs("a", { href: project.website_url, target: "_blank", rel: "noopener noreferrer", className: "inline-flex items-center gap-1 text-sm text-[hsl(var(--color-primary))] hover:underline font-medium", children: [_jsx("span", { className: "material-symbols-outlined text-[16px]", children: "language" }), project.website_url.replace(/^https?:\/\//, '')] }))] }), _jsxs("div", { className: "flex flex-col sm:flex-row flex-wrap gap-2 sm:gap-3 justify-center md:justify-start pt-2", children: [_jsx(AnalyzeBrandButton, { projectId: projectId }), _jsxs(Button, { variant: "outline", onClick: onEdit, children: [_jsx("span", { className: "material-symbols-outlined text-[18px]", children: "edit" }), "Editar manualmente"] })] })] })] })] }));
}
