import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { SOCIAL_ICON_MAP } from './utils';
export function BulletList({ text }) {
    if (!text)
        return null;
    const lines = text.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
    if (lines.length <= 1) {
        return (_jsx("p", { className: "text-sm text-slate-700 leading-relaxed whitespace-pre-wrap font-medium", children: text }));
    }
    return (_jsx("ul", { className: "space-y-2", children: lines.map((line, i) => (_jsxs("li", { className: "flex gap-2 text-sm text-slate-700 font-medium leading-relaxed", children: [_jsx("span", { className: "mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-gradient-to-br from-pink-500 to-cyan-500" }), _jsx("span", { children: line.replace(/^[-*•]\s*/, '') })] }, i))) }));
}
export function SectionTitle({ icon, children, autoGenerated = true, }) {
    return (_jsxs("div", { className: "flex items-center gap-2 sm:gap-3 mb-4", children: [_jsx("span", { className: "w-8 h-8 sm:w-10 sm:h-10 rounded-xl sm:rounded-2xl bg-gradient-to-br from-pink-100 to-cyan-100 grid place-items-center shrink-0", children: _jsx("span", { className: "material-symbols-outlined text-[18px] sm:text-[22px] text-[hsl(var(--color-primary))]", children: icon }) }), _jsx("h3", { className: "font-display text-base sm:text-xl font-black", children: children }), autoGenerated && (_jsx("span", { className: "material-symbols-outlined text-[14px] text-slate-400 cursor-help", title: "Este campo se genera autom\u00E1ticamente al analizar tu sitio web. Puedes editarlo manualmente.", children: "info" }))] }));
}
export function Row({ label, value, icon, }) {
    let emptyText = null;
    if (value === null || value === undefined) {
        emptyText = 'Sin información';
    }
    else if (typeof value === 'string' && !value.trim()) {
        emptyText = 'Aún no has completado este campo';
    }
    else if (Array.isArray(value) && value.length === 0) {
        emptyText = `Sin ${label.toLowerCase()} registrados`;
    }
    return (_jsxs("div", { className: "space-y-1.5", children: [_jsxs("p", { className: "text-[10px] font-black uppercase tracking-[0.2em] text-slate-500 flex items-center gap-1.5", children: [icon && (_jsx("span", { className: "material-symbols-outlined text-[14px] text-[hsl(var(--color-primary))]", children: icon })), label] }), emptyText !== null ? (_jsx("p", { className: "text-xs italic text-slate-400", children: emptyText })) : typeof value === 'string' ? (_jsx("p", { className: "text-sm text-slate-700 font-medium whitespace-pre-wrap leading-relaxed", children: value })) : (value)] }));
}
export function SocialIcon({ platform }) {
    const p = platform.toLowerCase();
    return (_jsx("span", { className: "material-symbols-outlined text-[18px]", children: SOCIAL_ICON_MAP[p] ?? 'link' }));
}
