import type { ReactNode } from 'react';
import { SOCIAL_ICON_MAP } from './utils';

export function BulletList({ text }: { text: string | null | undefined }) {
  if (!text) return null;
  const lines = text.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
  if (lines.length <= 1) {
    return (
      <p className="text-sm text-slate-700 leading-relaxed whitespace-pre-wrap font-medium">
        {text}
      </p>
    );
  }
  return (
    <ul className="space-y-2">
      {lines.map((line, i) => (
        <li key={i} className="flex gap-2 text-sm text-slate-700 font-medium leading-relaxed">
          <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-gradient-to-br from-pink-500 to-cyan-500" />
          <span>{line.replace(/^[-*•]\s*/, '')}</span>
        </li>
      ))}
    </ul>
  );
}

export function SectionTitle({
  icon,
  children,
  autoGenerated = true,
}: {
  icon: string;
  children: ReactNode;
  autoGenerated?: boolean;
}) {
  return (
    <div className="flex items-center gap-2 sm:gap-3 mb-4">
      <span className="w-8 h-8 sm:w-10 sm:h-10 rounded-xl sm:rounded-2xl bg-gradient-to-br from-pink-100 to-cyan-100 grid place-items-center shrink-0">
        <span className="material-symbols-outlined text-[18px] sm:text-[22px] text-[hsl(var(--color-primary))]">
          {icon}
        </span>
      </span>
      <h3 className="font-display text-base sm:text-xl font-black">{children}</h3>
      {autoGenerated && (
        <span
          className="material-symbols-outlined text-[14px] text-slate-400 cursor-help"
          title="Este campo se genera automáticamente al analizar tu sitio web. Puedes editarlo manualmente."
        >
          info
        </span>
      )}
    </div>
  );
}

export function Row({
  label,
  value,
  icon,
}: {
  label: string;
  value: ReactNode;
  icon?: string;
}) {
  let emptyText: string | null = null;
  if (value === null || value === undefined) {
    emptyText = 'Sin información';
  } else if (typeof value === 'string' && !value.trim()) {
    emptyText = 'Aún no has completado este campo';
  } else if (Array.isArray(value) && value.length === 0) {
    emptyText = `Sin ${label.toLowerCase()} registrados`;
  }
  return (
    <div className="space-y-1.5">
      <p className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-500 flex items-center gap-1.5">
        {icon && (
          <span className="material-symbols-outlined text-[14px] text-[hsl(var(--color-primary))]">
            {icon}
          </span>
        )}
        {label}
      </p>
      {emptyText !== null ? (
        <p className="text-xs italic text-slate-400">{emptyText}</p>
      ) : typeof value === 'string' ? (
        <p className="text-sm text-slate-700 font-medium whitespace-pre-wrap leading-relaxed">
          {value}
        </p>
      ) : (
        value
      )}
    </div>
  );
}

export function SocialIcon({ platform }: { platform: string }) {
  const p = platform.toLowerCase();
  return (
    <span className="material-symbols-outlined text-[18px]">
      {SOCIAL_ICON_MAP[p] ?? 'link'}
    </span>
  );
}
