/**
 * Utility to fix malformed Markdown tables generated by AI.
 * AI models sometimes return tables on a single line or with broken row separators.
 */
export function repairMarkdownTable(content: string): string {
  if (!content) return content;

  // 1. Normalize whitespace and newlines
  let repaired = content.replace(/\r\n/g, '\n').replace(/\t/g, ' ');

  // 2. Fix "Squashed Tables" - identify row ends and insert newlines
  // Rule A: Split after a normal cell followed by a pipe
  repaired = repaired.replace(/(\|[^|\n]+\|)\s*\|/g, '$1\n|');

  // Rule B: Specifically handle the separator row if Rule A missed it
  repaired = repaired.replace(/(\|[:\-\s]+\|)\s*\|/g, '$1\n|');

  // 3. Ensure tables start on a new line.
  repaired = repaired.replace(/([^\n])\s*(\|.*\|:?---)/g, '$1\n$2');

  // 4. Double check double pipes "||"
  repaired = repaired.replace(/\|\|/g, '|\n|');

  // 5. Structural Fix: Ensure header and separator rows have the same number of columns.
  // Markdown tables MUST have matching column counts in header and separator to render.
  const lines = repaired.split('\n');
  const finalLines = [...lines];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    // Check if it's a potential separator row: e.g. |:---|---:| or |---|
    // It should contain at least one pipe and only characters like |, :, -, and space.
    if (line.includes('|') && /^[|:\-\s]+$/.test(line) && line.includes('---')) {
      if (i > 0) {
        const header = lines[i - 1].trim();
        if (header.startsWith('|') && header.endsWith('|')) {
          const headerPipes = (header.match(/\|/g) || []).length;
          const separatorPipes = (line.match(/\|/g) || []).length;

          if (headerPipes > separatorPipes) {
            // AI missed some columns in the separator row. Add them.
            const missingCount = headerPipes - separatorPipes;
            const extension = Array(missingCount).fill('---').join('|') + '|';
            finalLines[i] = line + (line.endsWith('|') ? '' : '|') + extension;
          }
        }
      }
    }
  }

  repaired = finalLines.join('\n');

  // 6. Clean up: Ensure there is at least one newline between rows.
  repaired = repaired.replace(/(\|[:\-\s]+\|)\s*(\|)/g, '$1\n$2');

  return repaired;
}
