import { WebsiteAnalyzer } from './website-analyzer.js';
import { CompetitorAnalyzer } from './competitor-analyzer.js';
import { NewsAggregator } from './news-aggregator.js';
import { BrandSynthesizer } from './brand-synthesizer.js';
import { ContentEvaluator } from './content-evaluator.js';
import { ImageGenerator } from './image-generator.js';
import { InstagramScraper } from './instagram-scraper.js';
import { TikTokScraper } from './tiktok-scraper.js';
import { ImageAnalyzer } from './image-analyzer.js';
import { BrandOrchestrator } from './brand-orchestrator.js';
import { MarketDetector } from './market-detector.js';
import { AutoCompetitorDetector } from './auto-competitor-detector.js';
import { RecommendationGenerator } from './recommendation-generator.js';
import { TrendingFinder } from './trending-finder.js';
import { EmbeddingsService, embeddingsService } from './embeddings.js';

export const websiteAnalyzer = new WebsiteAnalyzer();
export const competitorAnalyzer = new CompetitorAnalyzer();
export const newsAggregator = new NewsAggregator();
export const brandSynthesizer = new BrandSynthesizer();
export const contentEvaluator = new ContentEvaluator();
export const imageGenerator = new ImageGenerator();
export const instagramScraper = new InstagramScraper();
export const tiktokScraper = new TikTokScraper();
export const imageAnalyzer = new ImageAnalyzer();
export const brandOrchestrator = new BrandOrchestrator();
export const marketDetector = new MarketDetector();
export const autoCompetitorDetector = new AutoCompetitorDetector();
export const recommendationGenerator = new RecommendationGenerator();
export const trendingFinder = new TrendingFinder();
export { embeddingsService };

export { WebsiteAnalyzer, CompetitorAnalyzer, NewsAggregator, BrandSynthesizer, ContentEvaluator, ImageGenerator, InstagramScraper, TikTokScraper, ImageAnalyzer, BrandOrchestrator, MarketDetector, AutoCompetitorDetector, RecommendationGenerator, TrendingFinder, EmbeddingsService };
export type { DetectTrendsInput, DetectTrendsResult, DetectedTrend, TrendCategory, TrendMomentum, TrendEvidence } from './trending-finder.js';
export type { GenerateRecommendationsInput } from './recommendation-generator.js';
export type { DetectMarketsInput, DetectMarketsResult } from './market-detector.js';
export type { AutoCompetitorDetectInput, AutoCompetitorResult, DetectedCompetitor } from './auto-competitor-detector.js';
export type { ImageVisualAnalysis } from './image-analyzer.js';
export type { BrandAnalysisResult } from './brand-orchestrator.js';
export type { WebsiteAnalysisResult, AnalyzeWebsiteInput } from './website-analyzer.js';
export type { CompetitorAnalysisResult, AnalyzeCompetitorInput } from './competitor-analyzer.js';
export type { NewsResult, NewsItem, AggregateNewsInput } from './news-aggregator.js';
export type { BrandSynthesisResult, SynthesizeBrandInput } from './brand-synthesizer.js';
export type { ContentEvaluationResult, EvaluateContentInput } from './content-evaluator.js';
export type { GenerateImageInput, GenerateImageOutput, GeneratedVariation, EditImageInput, EditImageOutput, ImageSize, ImageStyle, ImageModel } from './image-generator.js';
export type { ScrapeInstagramInput, ScrapeInstagramResult, ScrapedInstagramPost } from './instagram-scraper.js';
export type { ScrapeTikTokInput, ScrapeTikTokResult, ScrapedTikTokPost } from './tiktok-scraper.js';
export { parseInstagramHandle } from './instagram-scraper.js';
export { parseTikTokHandle } from './tiktok-scraper.js';
